DROP_OFF_TOPIC_PREFIX = "dropoff"

USER_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.user.events"
CATALOG_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.catalog.events"
MODERATION_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.moderation.events"
CART_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.cart.events"
ORDER_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.order.events"
PAYMENT_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.payment.events"
DELIVERY_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.delivery.events"
DAMAGE_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.damage.events"
NOTIFICATION_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.notification.events"
AUDIT_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.audit.events"

HEALTHCHECK_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.healthcheck"

ALL_TOPICS = [
    USER_EVENTS_TOPIC,
    CATALOG_EVENTS_TOPIC,
    MODERATION_EVENTS_TOPIC,
    CART_EVENTS_TOPIC,
    ORDER_EVENTS_TOPIC,
    PAYMENT_EVENTS_TOPIC,
    DELIVERY_EVENTS_TOPIC,
    DAMAGE_EVENTS_TOPIC,
    NOTIFICATION_EVENTS_TOPIC,
    AUDIT_EVENTS_TOPIC,
]