DROP_OFF_TOPIC_PREFIX = "dropoff"

USER_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.users.events"
ITEM_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.items.events"
MODERATION_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.moderation.events"
CART_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.cart.events"
ORDER_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.orders.events"
PAYMENT_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.payments.events"
DELIVERY_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.deliveries.events"
NOTIFICATION_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.notifications.events"
AUDIT_EVENTS_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.audit.events"

HEALTHCHECK_TOPIC = f"{DROP_OFF_TOPIC_PREFIX}.healthcheck"

ALL_TOPICS = [
    USER_EVENTS_TOPIC,
    ITEM_EVENTS_TOPIC,
    MODERATION_EVENTS_TOPIC,
    CART_EVENTS_TOPIC,
    ORDER_EVENTS_TOPIC,
    PAYMENT_EVENTS_TOPIC,
    DELIVERY_EVENTS_TOPIC,
    NOTIFICATION_EVENTS_TOPIC,
    AUDIT_EVENTS_TOPIC,
]