
"""add catalog indexes and public catalog api

Revision ID: 658b5990b04f
Revises: 0005_fix_item_images_created_at
Create Date: 2026-04-09 12:01:25.454665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '658b5990b04f'
down_revision: Union[str, None] = '0005_fix_item_images_created_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.alter_column('item_images', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('item_images', 'mime_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item_images', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('item_images_item_id_fkey'), 'item_images', type_='foreignkey')
    op.create_foreign_key(None, 'item_images', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_city'), 'items', ['city'], unique=False)
    op.create_index(op.f('ix_items_created_at'), 'items', ['created_at'], unique=False)
    op.create_index(op.f('ix_items_daily_price_cents'), 'items', ['daily_price_cents'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_index('ix_items_status_created_at', 'items', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_status_created_at', table_name='items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_daily_price_cents'), table_name='items')
    op.drop_index(op.f('ix_items_created_at'), table_name='items')
    op.drop_index(op.f('ix_items_city'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_constraint(None, 'item_images', type_='foreignkey')
    op.create_foreign_key(op.f('item_images_item_id_fkey'), 'item_images', 'items', ['item_id'], ['id'])
    op.alter_column('item_images', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('item_images', 'mime_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('item_images', 'url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
