
"""add catalog indexes and public catalog api

Revision ID: 80c9576401f9
Revises: 658b5990b04f
Create Date: 2026-04-09 13:26:43.870367
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80c9576401f9'
down_revision: Union[str, None] = '658b5990b04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
