
"""add deliveries

Revision ID: 968855a3c99b
Revises: 0010_outbox_events
Create Date: 2026-05-14 12:05:35.013251
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '968855a3c99b'
down_revision: Union[str, None] = '0010_outbox_events'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('renter_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('courier_name', sa.String(length=255), nullable=True),
    sa.Column('current_location', sa.String(length=500), nullable=True),
    sa.Column('final_location', sa.String(length=500), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_item_id'), 'deliveries', ['item_id'], unique=False)
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=False)
    op.create_index(op.f('ix_deliveries_order_item_id'), 'deliveries', ['order_item_id'], unique=True)
    op.create_index(op.f('ix_deliveries_owner_id'), 'deliveries', ['owner_id'], unique=False)
    op.create_index(op.f('ix_deliveries_renter_id'), 'deliveries', ['renter_id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.drop_index(op.f('ix_item_images_item_id'), table_name='item_images')
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.drop_index(op.f('ix_outbox_events_aggregate'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_topic'), table_name='outbox_events')
    op.create_index(op.f('ix_payment_transactions_created_at'), 'payment_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_stripe_checkout_sessions_created_at'), 'stripe_checkout_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_stripe_payment_intents_created_at'), 'stripe_payment_intents', ['created_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_payment_intents_created_at'), table_name='stripe_payment_intents')
    op.drop_index(op.f('ix_stripe_checkout_sessions_created_at'), table_name='stripe_checkout_sessions')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payment_transactions_created_at'), table_name='payment_transactions')
    op.create_index(op.f('ix_outbox_events_topic'), 'outbox_events', ['topic'], unique=False)
    op.create_index(op.f('ix_outbox_events_status_created_at'), 'outbox_events', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate'), 'outbox_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.create_index(op.f('ix_item_images_item_id'), 'item_images', ['item_id'], unique=False)
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_renter_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_owner_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_order_item_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_item_id'), table_name='deliveries')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
